[package]
name = "aoc-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = "0.4.6"
petgraph = { version = "0.8.3", features = ["rayon"] }
geo = "0.32.0"
good_lp = { version = "1.14.2", default-features = false, features = ["microlp"] }
