[package]
name = "aoc-0000"
version = "0.1.0"
edition = "2024"
description = "Default template for every year of Advent of Code."

[dependencies]
parameterized = "2.1.0"
aoc-lib = { path = "../aoc-lib" }
aoc-macro = { path = "../aoc-macro" }